### ISSUE TITLE
Cant start MadQtProjectManager

### ISSUE THREAD

**Issue by EdwinFairchild** [MadPonyInteractive/MadQt#6]
Hey there first of all thanks for all the videos and this plugin.
I believe I have successfully installed the plug in shown below:
```
eddie@DeusXMachina:~$ pip install MadQt
Defaulting to user installation because normal site-packages is not writeable
Collecting MadQt
  Downloading MadQt-0.0.31-py3-none-any.whl (188 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 188.3/188.3 KB 7.8 MB/s eta 0:00:00
Collecting pyinstaller>=4.7
  Downloading pyinstaller-5.1-py3-none-manylinux2014_x86_64.whl (547 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 547.4/547.4 KB 15.2 MB/s eta 0:00:00
Collecting PySide6>=6.0.0
  Downloading PySide6-6.3.1-cp36-abi3-manylinux_2_28_x86_64.whl (65 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 65.9/65.9 KB 14.7 MB/s eta 0:00:00
Requirement already satisfied: Pillow>=8.3.0 in /usr/lib/python3/dist-packages (from MadQt) (9.0.1)
Collecting altgraph
  Downloading altgraph-0.17.2-py2.py3-none-any.whl (21 kB)
Collecting pyinstaller-hooks-contrib>=2021.4
  Downloading pyinstaller_hooks_contrib-2022.7-py2.py3-none-any.whl (234 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 234.3/234.3 KB 20.5 MB/s eta 0:00:00
Requirement already satisfied: setuptools in /usr/lib/python3/dist-packages (from pyinstaller>=4.7->MadQt) (59.6.0)
Collecting shiboken6==6.3.1
  Downloading shiboken6-6.3.1-cp36-abi3-manylinux_2_28_x86_64.whl (227 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 227.5/227.5 KB 15.2 MB/s eta 0:00:00
Collecting PySide6-Addons==6.3.1
  Downloading PySide6_Addons-6.3.1-cp36-abi3-manylinux_2_28_x86_64.whl (120.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 120.1/120.1 MB 20.5 MB/s eta 0:00:00
Collecting PySide6-Essentials==6.3.1
  Downloading PySide6_Essentials-6.3.1-cp36-abi3-manylinux_2_28_x86_64.whl (76.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 76.1/76.1 MB 28.3 MB/s eta 0:00:00
Installing collected packages: altgraph, shiboken6, pyinstaller-hooks-contrib, PySide6-Essentials, pyinstaller, PySide6-Addons, PySide6, MadQt
Successfully installed MadQt-0.0.31 PySide6-6.3.1 PySide6-Addons-6.3.1 PySide6-Essentials-6.3.1 altgraph-0.17.2 pyinstaller-5.1 pyinstaller-hooks-contrib-2022.7 shiboken6-6.3.1

```

Next I ran the manager command and got the following error. Any insight would be helpful. I am  using this on latest  Ubuntu

```
eddie@DeusXMachina:~$ MadQtProjectManager 
Traceback (most recent call last):
  File "/home/eddie/.local/bin/MadQtProjectManager", line 8, in <module>
    sys.exit(main())
  File "/home/eddie/.local/lib/python3.10/site-packages/MadQt/scripts/ProjectManager.py", line 5, in main
    subprocess.check_output(["python","main.py"])
  File "/usr/lib/python3.10/subprocess.py", line 420, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.10/subprocess.py", line 501, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.10/subprocess.py", line 966, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1842, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'python'

```

**Comment by EdwinFairchild** [comment]
I have also installed Python on Windows now from the Microsoft store and ran the same steps. I import MadQt from the terminal and get the Success message but designer does not show the plug in.  I know MS App store probably does not install Python in same directory as a Python online installer .. Does the plugin use some "default" directory where it thinks python is installed ?

**Comment by MadPonyInteractive** [comment]
I wish you had come around sooner, I kinda abandoned this project for the time being as Im really busy working with blender api. I couldnt really help you at this point as I havent touched this for a while. For what I recall if you look at the source files the __init__.py most likely you will notice a few init functions that set up the necessary variables. If you watch my videos on pyQt and have a look trough the code Im sure you will figure it out. I never tested it on macOs. 

I might come back to this project at a later date if the interest rises but if you understand the source code you will see it has potential and you can even make it your own.

Hope that is of any help.

**Comment by EdwinFairchild** [comment]
Alright no worries , I know the feeling, I sometimes abandon projects once the interest fizzles out hahaha. Thanks ill look into it. But should be able to use the MadQt container without necessarily needing QT designer correct?

**Comment by MadPonyInteractive** [comment]
QtDesigner is installed with the packages when you install MadQt, you will need to look for it in the site packages/ pyside6 I believe
